package package1;
// Generated Dec 8, 2017 8:49:07 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "Currency", catalog = "Deposits")
public class Currency implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Program> programs = new HashSet<Program>(0);

	public Currency() {
	}

	public Currency(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Currency(int id, String name, Set<Program> programs) {
		this.id = id;
		this.name = name;
		this.programs = programs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<Program> getPrograms() {
		return this.programs;
	}

	public void setPrograms(Set<Program> programs) {
		this.programs = programs;
	}

}
