package package1;
// Generated Dec 8, 2017 8:49:07 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "Program", catalog = "Deposits")
public class Program implements java.io.Serializable {

	private int id;
	private Bank bank;
	private Currency currency;
	private int term;
	private double percentage;
	private String programName;

	public Program() {
	}

	public Program(int id, Bank bank, Currency currency, int term, double percentage, String programName) {
		this.id = id;
		this.bank = bank;
		this.currency = currency;
		this.term = term;
		this.percentage = percentage;
		this.programName = programName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idBank", nullable = false)
	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCurrency", nullable = false)
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@Column(name = "Term", nullable = false)
	public int getTerm() {
		return this.term;
	}

	public void setTerm(int term) {
		this.term = term;
	}

	@Column(name = "Percentage", nullable = false, precision = 53, scale = 0)
	public double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}

	@Column(name = "ProgramName", nullable = false, length = 50)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

}
